# <b> NUMERIC DATA ANALYSIS WITH NUMPY </b>

In [22]:
import numpy as np #type: ignore

In [2]:
# Membuat Array
a = np.array([1, 2, 3, 4, 5])
print(a)


[1 2 3 4 5]


In [3]:
# Membuat Array Multi Dimensi
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
# Array dengan value 0 dan 1
zeros = np.zeros((3,3))
ones = np.ones((3,3))
print(zeros)
print("==============")
print(ones)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
# Array dengan range
range_array = np.arange(0, 10, 2)
print(range_array)

[0 2 4 6 8]


In [6]:
# Array dengan nilai acak
random_array = np.random.rand(3,3)
print(random_array)

[[0.98996893 0.69281082 0.0224579 ]
 [0.13552869 0.25134312 0.49127847]
 [0.58874278 0.29879056 0.46245185]]


# <b>OPERASI DASAR PADA ARRAY</b>

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b) # Penjumlahan
print(a - b) # Pengurangan
print(a * b) # Perkalian
print(a / b) # Pembagian
print(a ** 2) # kuadrat

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [8]:
# Operasi Statistik
data = np.array([1, 2, 3, 4, 5])

print(np.mean(data)) # Rata-rata
print(np.median(data)) # Median
print(np.std(data)) # Standar Deviasi
print(np.var(data)) # Variance
print(np.sum(data)) # Jumlah Elemen
print(np.min(data)) # Nilai Minimum
print(np.max(data)) # Nilai Maksimum

3.0
3.0
1.4142135623730951
2.0
15
1
5


In [9]:
# Operasi Matriks
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A, B)) # Perkalian Matriks
print("==============")
print(np.transpose(A)) # Transpose Matriks
print("==============")
print(A. T) # Transpose Matriks
print("==============")
print(np.linalg.inv(A)) # Invers Matriks

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


# <b>INDEXING, SLICING, DAN ITERASI </b>

In [10]:
# Indexing dan Slicing
data = np.array([1, 2, 3, 4, 5])

print(data[0]) # Indexing Elemen Pertama
print(data[-1]) # Indexing Elemen Terakhir
print(data[1:4]) # Subset dari elemen kedua hingga keempat


1
5
[2 3 4]


In [11]:
# Indexing array multi dimensi
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(data[1, 2]) # Elemen baris kedua, kolom ketiga
print(data[:, 0]) # Semua elemen pada kolom pertama
print(data[0, :]) # Semua elemen pada baris pertama

6
[1 4 7]
[1 2 3]


# <b>ITERASI PADA ARRAY</b>

In [12]:
for element in data.flat:
    print(element)

1
2
3
4
5
6
7
8
9


# <b>MENGUBAH BENTUK ARRAY</b>

In [13]:
# Reshape Array
data = np.array([1, 2, 3, 4, 5, 6])
reshaped_data = data.reshape(2, 3)
print(reshaped_data)

[[1 2 3]
 [4 5 6]]


In [14]:
# Menggabungkan dan Memishkan Array
data1 = np.array([1, 2, 3])
data2 = np.array([4, 5, 6])

# Menggabungkan Array
combined = np.concatenate((data1, data2))
print(combined)

# Memisahkan Array
split_array = np.array_split(combined, 2)
print(split_array)

[1 2 3 4 5 6]
[array([1, 2, 3]), array([4, 5, 6])]


# <b> OPERASI KONDISIONAL </b>

In [15]:
data = np.array([1, 2, 3, 4, 5, 6])

print(data[data > 3]) # Elemen yang lebih besar dari 3
print(np.where(data > 3, 1, 0)) # Mengubah elemen yang lebih besar dari 3 menjadi 1, dan sisanya menjadi 0

[4 5 6]
[0 0 0 1 1 1]


# <b>NUMPY UNTUK ANALISIS DATA NUMERIK</b>

In [16]:
penjualan = np.array([100, 120, 140, 160, 180])

# Statistik Dasar
print("Rata-rata Penjualan:", np.mean(penjualan))
print("Penjualan tertinggi:", np.max(penjualan))
print("Penjualan terendah:", np.min(penjualan))
print("Standar Deviasi Penjualan:", np.std(penjualan))

Rata-rata Penjualan: 140.0
Penjualan tertinggi: 180
Penjualan terendah: 100
Standar Deviasi Penjualan: 28.284271247461902


<b> NORMALISASI DATA </B>

In [17]:
data = np.array([1, 2, 3, 4, 5])

# Normalusasi data (nilai antara 0 dan 1)
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized_data)

[0.   0.25 0.5  0.75 1.  ]


# <b> LATIHAN </b>

1. Buat array berisi nilai tinggi siswa, kemudian hitung rata-rata, nilai maksimum, minimum, dan standar deviasi.
2. Buat array acak dengan ukuran 10x10, lalu cari nilai maksimum dan minimum di setiap baris.
3. Buat matriks 3x3 yang berisi nilai dari 1 hingga 9, kemudian hitung determinan dari matriks tersebut.
4. Normalisasikan array yang berisi data penghasilan karyawan agar berada dalam rentang 0 hingga 1.

In [18]:
# Latihan Nomor 1

# Membuat array berisi nilai tinggi siswa
tinggi_siswa = np.array([160, 165, 170, 175, 180])

# Menghitung rata-rata
rata_rata = np.mean(tinggi_siswa)
print("Rata-rata tinggi siswa:", rata_rata)

# Menghitung nilai maksimum
nilai_maksimum = np.max(tinggi_siswa)
print("Nilai maksimum tinggi siswa:", nilai_maksimum)

# Menghitung nilai minimum
nilai_minimum = np.min(tinggi_siswa)
print("Nilai minimum tinggi siswa:", nilai_minimum)

# Menghitung standar deviasi
standar_deviasi = np.std(tinggi_siswa)
print("Standar deviasi tinggi siswa:", standar_deviasi)

Rata-rata tinggi siswa: 170.0
Nilai maksimum tinggi siswa: 180
Nilai minimum tinggi siswa: 160
Standar deviasi tinggi siswa: 7.0710678118654755


In [19]:
# Latihan Nomor 2

# Membuat array acak dengan ukuran 10x10
array_acak = np.random.rand(10, 10)

# Mencari nilai maksimum dan minimum di setiap baris
nilai_maksimum_per_baris = np.max(array_acak, axis=1)
nilai_minimum_per_baris = np.min(array_acak, axis=1)

print("Array Acak 10x10:\n", array_acak)
print("Nilai maksimum di setiap baris:\n", nilai_maksimum_per_baris)
print("Nilai minimum di setiap baris:\n", nilai_minimum_per_baris)

Array Acak 10x10:
 [[8.96786342e-01 5.36849553e-01 9.99690172e-01 8.16401745e-01
  9.79408089e-01 1.92190122e-01 6.22138090e-04 5.14986909e-03
  5.07554246e-02 6.24626636e-01]
 [6.68835913e-02 5.40012269e-01 6.15823502e-01 2.89981655e-01
  5.26746748e-01 7.44080426e-01 1.08206793e-01 4.03484194e-01
  6.65816588e-02 2.89499116e-01]
 [9.01057148e-01 2.38792265e-01 2.12620342e-01 4.23869998e-01
  3.98249333e-01 2.45561055e-01 5.13155051e-01 7.17495227e-01
  8.64672056e-01 1.75602685e-01]
 [7.64286119e-01 2.46615065e-01 5.54317734e-01 4.72059355e-01
  3.92468252e-01 5.08665905e-02 9.05053939e-01 9.80543280e-01
  4.55822125e-01 7.51497682e-01]
 [4.67793448e-01 7.79826925e-01 2.62740453e-01 7.44700560e-01
  6.80660439e-01 1.71698952e-01 4.70886405e-01 6.94737403e-01
  1.15574329e-01 2.27139990e-01]
 [1.06356798e-02 1.82107803e-01 3.82938155e-01 3.63800584e-02
  5.56501605e-02 1.41080414e-01 1.44756163e-01 7.35795943e-01
  6.39809080e-01 5.13741469e-01]
 [3.11088692e-01 5.78125417e-01 7.23576

In [20]:
# Latihan Nomor 3

A = [[1,2,3],
     [4,5,6],
     [7,8,9]]

# Determinan Matriks A
determinan = np.linalg.det(A)

print("Determinan Matriks A:", determinan)

Determinan Matriks A: 0.0


In [21]:
# Latihan Nomor 4
